# Generated by Django 4.2.1 on 2023-05-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('admission_number', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('semester', models.PositiveIntegerField()),
                ('registration_number', models.CharField(max_length=20)),
                ('registration_certificate_photo', models.ImageField(upload_to='photos')),
                ('license_photo', models.ImageField(upload_to='photos')),
                ('insurance_photo', models.ImageField(upload_to='photos')),
                ('owner_declaration_photo', models.ImageField(upload_to='photos')),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
