# Generated by Django 4.2.1 on 2023-05-22 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_studentvehicle_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentvehicle',
            name='user',
        ),
    ]
