# Generated by Django 4.2.1 on 2023-05-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='submitted_by',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
