# Generated by Django 4.2.1 on 2023-05-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_booking_submitted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='submitted_by',
        ),
    ]
