# Generated by Django 4.2.1 on 2023-05-23 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_booking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.booking')),
            ],
        ),
    ]
