# Generated by Django 4.2.1 on 2023-05-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_pass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pass',
        ),
    ]
