# Generated by Django 4.2.1 on 2023-05-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
