# Generated by Django 4.2.1 on 2023-05-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_booking_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
